# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 26, 15, 39, 32, 961735, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 26, 15, 39, 48, 874544, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
