# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
